In [15]:
import pandas as pd

df = pd.read_csv('Zomato-data-.csv' , encoding='latin-1')
print(df.head())
print(df.shape)

                    name online_order book_table   rate  votes  \
0                  Jalsa          Yes        Yes  4.1/5    775
1         Spice Elephant          Yes         No  4.1/5    787
2        San Churro Cafe          Yes         No  3.8/5    918
3  Addhuri Udupi Bhojana           No         No  3.7/5     88
4          Grand Village           No         No  3.8/5    166

   approx_cost(for two people) listed_in(type)
0                          800          Buffet
1                          800          Buffet
2                          800          Buffet
3                          300          Buffet
4                          600          Buffet
(148, 7)

In [20]:
print(df.isnull().sum())
print(df.dtypes)

name                           0
online_order                   0
book_table                     0
rate                           0
votes                          0
approx_cost(for two people)    0
listed_in(type)                0
dtype: int64
name                           object
online_order                   object
book_table                     object
rate                           object
votes                           int64
approx_cost(for two people)     int64
listed_in(type)                object
dtype: object

In [21]:
print(df)

                      name online_order book_table   rate  votes  \
0                    Jalsa          Yes        Yes  4.1/5    775
1           Spice Elephant          Yes         No  4.1/5    787
2          San Churro Cafe          Yes         No  3.8/5    918
3    Addhuri Udupi Bhojana           No         No  3.7/5     88
4            Grand Village           No         No  3.8/5    166
..                     ...          ...        ...    ...    ...
143       Melting Melodies           No         No  3.3/5      0
144        New Indraprasta           No         No  3.3/5      0
145           Anna Kuteera          Yes         No  4.0/5    771
146                 Darbar           No         No  3.0/5     98
147          Vijayalakshmi          Yes         No  3.9/5     47

     approx_cost(for two people) listed_in(type)
0                            800          Buffet
1                            800          Buffet
2                            800          Buffet
3                            300          Buffet
4                            600          Buffet
..                           ...             ...
143                          100          Dining
144                          150          Dining
145                          450          Dining
146                          800          Dining
147                          200          Dining

[148 rows x 7 columns]

In [22]:
# Step 1: "/5" part remove
# "4.1/5" → "4.1"
df['rate'] = df['rate'].str.replace('/5', '')

# Step 2: Extra spaces remove
# " 4.1 " → "4.1"
df['rate'] = df['rate'].str.strip()

# Step 3: String → Number convert
# "4.1" → 4.1
df['rate'] = pd.to_numeric(df['rate'], errors='coerce')

print(df['rate'].head())

0    4.1
1    4.1
2    3.8
3    3.7
4    3.8
Name: rate, dtype: float64

In [23]:
print(df['rate'].dtype)

float64

In [26]:
df.nlargest(10, 'votes')[['name', 'votes']]

                  name  votes
38   Empire Restaurant   4884
86       Meghana Foods   4401
7               Onesta   2556
44              Onesta   2556
65         Kabab Magic   1720
37     Szechuan Dragon   1647
54        Roving Feast   1047
2      San Churro Cafe    918
14     San Churro Cafe    918
67  Gustoes Beer House    868

In [27]:
print(df['online_order'].value_counts())

online_order
No     90
Yes    58
Name: count, dtype: int64

In [28]:
print(df)

                      name online_order book_table  rate  votes  \
0                    Jalsa          Yes        Yes   4.1    775
1           Spice Elephant          Yes         No   4.1    787
2          San Churro Cafe          Yes         No   3.8    918
3    Addhuri Udupi Bhojana           No         No   3.7     88
4            Grand Village           No         No   3.8    166
..                     ...          ...        ...   ...    ...
143       Melting Melodies           No         No   3.3      0
144        New Indraprasta           No         No   3.3      0
145           Anna Kuteera          Yes         No   4.0    771
146                 Darbar           No         No   3.0     98
147          Vijayalakshmi          Yes         No   3.9     47

     approx_cost(for two people) listed_in(type)
0                            800          Buffet
1                            800          Buffet
2                            800          Buffet
3                            300          Buffet
4                            600          Buffet
..                           ...             ...
143                          100          Dining
144                          150          Dining
145                          450          Dining
146                          800          Dining
147                          200          Dining

[148 rows x 7 columns]

In [29]:
print(df.groupby('listed_in(type)')['rate'].mean().sort_values(ascending=False))

listed_in(type)
other     3.912500
Buffet    3.842857
Cafes     3.765217
Dining    3.571818
Name: rate, dtype: float64

In [31]:
print(df.groupby('approx_cost(for two people)')['name'].count())

approx_cost(for two people)
100     6
150    16
200    16
250     6
300    23
350     3
400    15
450     6
500    14
550     3
600    13
650     2
700     5
750     3
800    12
850     2
900     2
950     1
Name: name, dtype: int64

In [32]:
df['approx_cost(for two people)'].value_counts()

approx_cost(for two people)
300    23
150    16
200    16
400    15
500    14
600    13
800    12
250     6
100     6
450     6
700     5
350     3
550     3
750     3
900     2
650     2
850     2
950     1
Name: count, dtype: int64

In [33]:
df.to_csv('zomato_clean.csv', index=False)
print("Saved!")

Saved!

In [34]:
print(df)

                      name online_order book_table  rate  votes  \
0                    Jalsa          Yes        Yes   4.1    775
1           Spice Elephant          Yes         No   4.1    787
2          San Churro Cafe          Yes         No   3.8    918
3    Addhuri Udupi Bhojana           No         No   3.7     88
4            Grand Village           No         No   3.8    166
..                     ...          ...        ...   ...    ...
143       Melting Melodies           No         No   3.3      0
144        New Indraprasta           No         No   3.3      0
145           Anna Kuteera          Yes         No   4.0    771
146                 Darbar           No         No   3.0     98
147          Vijayalakshmi          Yes         No   3.9     47

     approx_cost(for two people) listed_in(type)
0                            800          Buffet
1                            800          Buffet
2                            800          Buffet
3                            300          Buffet
4                            600          Buffet
..                           ...             ...
143                          100          Dining
144                          150          Dining
145                          450          Dining
146                          800          Dining
147                          200          Dining

[148 rows x 7 columns]